global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'otienomarvin7@gmail.com'
  smtp_auth_username: 'otienomarvin7@gmail.com'
  smtp_auth_password: ''
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
  - name: 'send_email'
    email_configs:
      - to: nyalik.marvoh@gmail.com
        require_tls: false
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
