version: '3'
services:
  db:
    image: postgres:16.1-alpine
    container_name: demo-postgres-14.2
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/app/lib/data
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  lyrical-labyrinth:
    image: vegasmarvin/lyrical_labyrinth:v1.0
    container_name: lyrical-labyrinth
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - app_storage:/store

volumes:
  postgres_data: {}
  app_storage: {}
  redis_data: {}
