version: '3'
services:
  db:
    image: postgres:16.1-alpine
    container_name: postgres_cont
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=lyrical_lab_prod
      - POSTGRES_USER=marvin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/app/lib/data
    networks:   
      - my-network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:   
      - my-network

  lyrical-labyrinth:
    image: vegasmarvin/lyrical_labyrinth:v1.0
    container_name: lyrical-labyrinth
    command: "./bin/rails server"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=lyrical_lab_prod
      - POSTGRES_USER=marvin
      - POSTGRES_PASSWORD=password
      - RAILS_MASTER_KEY=a4d22b57d9981ff136b0bf4c4e8533b9
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    volumes:
      - app_storage:/store
    networks: 
      - my-network

  nginx:
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "8000:8000"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - lyrical-labyrinth
    networks: 
      - my-network

networks:   
  my-network:

volumes:
  postgres_data: {}
  app_storage: {}
  redis_data: {}
