apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXN1c2Vy
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==
  RAILS_MASTER_KEY: YTRkMjJiNTdkOTk4MWZmMTM2YjBiZjRjNGU4NTMzYjk=